name: Acción compuesta
description: 'Acción de tirada de dados'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Prueba con GH-CLI
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh issue list
    - name: Prueba con llamada HTTP
      shell: bash
      run: |
        curl https://api.github.com/repos/${{ github.repository }}/issues \
        -H 'authorization: Bearer ${{ github.token }}' \
        -H 'content-type: application/json'